"""add_job_description_scoring_rubric_to_interview_summaries

Revision ID: 480a265e5923
Revises: 8ba95b973a4a
Create Date: 2026-05-11 20:13:56.090073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '480a265e5923'
down_revision: Union[str, None] = '8ba95b973a4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_summaries', sa.Column('job_description', sa.Text(), nullable=True))
    op.add_column('interview_summaries', sa.Column('scoring_rubric', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_summaries', 'scoring_rubric')
    op.drop_column('interview_summaries', 'job_description')
    # ### end Alembic commands ###
